screenshot: true
screenshot_url_parameters:
  host: 'localhost'
  port: '3000'

sidekiq: {}

action_mailer:
  default_options:
    from: "example-team@example.com"
  default_url_options:
    host: "example.com"

project_roles:
  - admin
  - owner
  - manager
  - editor
  - viewer
